fuego-dev/firecam

- gcf_ffmpeg/index.js
Also remove some leftover sample code
> ffmpeg: wait to send HTTP response until all is done

- alertwildfire_get_cont_obs.py
- lib/alertwildfire_API.py
implementation of tim's continual observation request
> alertwildfire continual observation request

- get_image_hpwren.py
- image_crop/recrop_min_size.py
- lib/img_archive.py
minusMinutes code in recrop_min_size was using old deleted
HPWREN interface, so updated the code to use the new interface.
Also, factored out some common code to img_archive.py
> Fix bitrotted code for minusMinutes

- lib/db_manager.py
- lib/img_archive.py
Schema for image archive DB and simple insert function
> Image archive DB support

- smoke-classifier/detect_fire.py
The queue length is more stable now that images are inserted if queue
is not full and an old image is being processed.
Also, code cleanup and reorg
> detect_fire: Fix minusMinutes queue management

- lib/img_archive.py
- smoke-classifier/detect_fire.py
This change adds support for detect_fire.py to pull random images
from HPWREN archive from given time range to collect positives from
past images to retrain faster.
> detect_fire.py with archived images

- lib/db_manager.py
- notification_mgmt.py
Stores who to notify by email and phone and when
notifcation_mgmt.py is a simple app to update the table
Still to come are the changes to detect_fire.py to use this table.
> notification db table

- lib/db_manager.py
- lib/email_helper.py
- notification_mgmt.py
- smoke-classifier/detect_fire.py
Check notification DB for active emails and active phone sms/text
messages.  Also, emails are now sent as bcc as we may have multiple
viewers who may not wish to know or be known.
> Use notification DB for alerts

- smoke-classifier/detect_fire.py
Attach a few successive images to alert emails so reviewers can use
temporal change to evaluate smoke.
Some related cleanup
> Multiple successive images in alert emails

- lib/email_helper.py
Seeing email send failures, so let's see if retry fixes it.
> Retry email send attempts

- lib/email_helper.py
Have to use to this special method due to large image attachments
in our emails.
> Use uploadType=resumable for sending emails

- lib/db_manager.py
- smoke-classifier/detect_fire.py
Previously the code was using multiple insert statements in a single
transaction.  This works efficiently on some systems, but not
everywhere, so the new code now inserts multiple rows in a single insert
statement.
> Optimze inserting scores into SQL

- google_cloud/firecam_detect.service
- google_cloud/setup_vm.sh
setup_vm.sh installs various packages and files in the right places
firecam_detect.service is a systemd config file to manage detection
service
> Setup files for google cloud VM installation

- lib/sms_helper.py
I noticed there were some failures that were crashing detect_fire.py
process, so adding graceful error handling and retries.
> Retry loop for sending sms

- alertwildfire_live_recording.py
- lib/alertwildfire_API.py
disabled md5, allowed for scale-able averaging(response time),allowed option to separate refresh times based on type
> much needed updates

- smoke-classifier/detect_fire.py
The earlier 2 hour window was too long and because it was based on
alerts vs detections it also didn't handle long lasting fires.
New code now checks for 1 hour window of no new detections.
> Improve suppression logic

- camera_mgmt.py
This file was using an older style of DB connection, so just
updating it to match new code.
> camera_mgmt: Update db setup

- gdrive_xfer.py
Google changed something such that the existing batch size of 100
was triggering frequent http 500 internal errors.  Reducing the batch
size helps reduce the errors, but it's still not completely error proof.
Batch size is now set to 25, and gets most of the performance benefit
with minimal errors.
> gdrive_xfer: Reduce batch size

- diff_images.py
out = a - b with 128 offset to avoid truncation of negative values
> diff_images: simple wrapper around diff code

- smoke-classifier/detect_fire.py
The deferred queue wasn't very reliable in timing, and now we have
working archive access to both HPWREN and Alert, so we'll use that
when resurrecting minusMinutes functionality.
> detect_fire: delete deferred images queue

- .gitignore
- lib/img_archive.py
I added an index on the table in the DB, and this change adds time
range limits to the query that further speeds up things.
> img_archive: Speed up Alert Archive queries
